import { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { SessionProvider } from "next-auth/react";
import FarmerNavbar from "./farmer/components/Navbar";
import MSMENavbar from "../../components/Navbar";
import Navbar from "./components/Navbar";
import { auth } from '@/auth';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();  // Fetch session information

  return (
    <html lang="en">
      <body>
        {/* Wrap your app with SessionProvider */}
        <SessionProvider>
          {/* Conditional Navbar Rendering */}
          {session ? (
            session.user.type === "farmer" ? (
              <FarmerNavbar />
            ) : (
              <MSMENavbar />
            )
          ) : (
            <Navbar />
          )}
          {children}
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
