import { auth } from '@/auth';
import { Toaster } from "@/components/ui/sonner";
import { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();  // Fetch session information

  return (
    <html lang="en">
      <body>
        {/* Wrap your app with SessionProvider */}
        <SessionProvider>
          {children}
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
